import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'
import './globals.css'
import 'bootstrap/dist/css/bootstrap.css'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        <div className="container-fluid">
        {children}
        </div>
        <Footer/>
        </body>
    </html>
  )
}
